apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: secureapp
  namespace: secureapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: secureapp
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
